source "https://api.berkshelf.com"

cookbook 'apt',             '2.4.0'
cookbook 'yum',             '3.2.2'
cookbook 'sudo',            '2.6.0'
cookbook 'yum-epel',        '0.4.0'
cookbook 'build-essential', '1.4.2'
cookbook 'selinux',         '0.8.0'
cookbook 'xfs',             '1.1.0'
cookbook 'hostsfile',       '~> 2.4.5'
cookbook 'haproxy',         '~> 1.6.6'
cookbook 'java',            '~> 1.29.0'
cookbook 'logstash',        '~> 0.11.2'
cookbook 'kibana_lwrp',     '~> 2.0.0'
cookbook 'elasticsearch',   '~> 0.3.13'

cookbook 'percona',  git: 'https://github.com/mevansam/chef-percona'
cookbook 'rabbitmq', git: 'https://github.com/kennonkwok/rabbitmq.git'
cookbook 'statsd',   git: 'https://github.com/att-cloud/cookbook-statsd'

cookbook 'openstack-common',         git: 'https://github.com/stackforge/cookbook-openstack-common',         branch: 'stable/icehouse'
cookbook 'openstack-identity',       git: 'https://github.com/stackforge/cookbook-openstack-identity',       branch: 'stable/icehouse'
cookbook 'openstack-object-storage', git: 'https://github.com/stackforge/cookbook-openstack-object-storage', branch: 'stable/icehouse'
cookbook 'openstack-ops-database',   git: 'https://github.com/stackforge/cookbook-openstack-ops-database',   branch: 'stable/icehouse'
cookbook 'openstack-ops-messaging',  git: 'https://github.com/stackforge/cookbook-openstack-ops-messaging',  branch: 'stable/icehouse'
cookbook 'openstack-orchestration',  git: 'https://github.com/stackforge/cookbook-openstack-orchestration',  branch: 'stable/icehouse'
cookbook 'openstack-telemetry',      git: 'https://github.com/stackforge/cookbook-openstack-telemetry',      branch: 'stable/icehouse'

cookbook 'openstack-image',          git: 'https://github.com/mevansam/chef-cookbook-openstack-image.git',     branch: 'stable/icehouse'
cookbook 'openstack-block-storage',  git: 'https://github.com/mevansam/chef-cookbook-openstack-block-storage', branch: 'stable/icehouse'
cookbook 'openstack-compute',        git: 'https://github.com/mevansam/chef-cookbook-openstack-compute.git',   branch: 'stable/icehouse'
cookbook 'openstack-network',        git: 'https://github.com/mevansam/chef-cookbook-openstack-network.git'    branch: 'stable/icehouse'
cookbook 'openstack-dashboard',      git: 'https://github.com/mevansam/chef-cookbook-openstack-dashboard',     branch: 'stable/icehouse'

cookbook 'sysutils', git: 'https://github.com/mevansam/chef-cookbook-sysutils.git'
cookbook 'cluster', git: 'https://github.com/mevansam/chef-cookbook-cluster.git'
cookbook 'compute',  git: 'https://github.com/mevansam/chef-cookbook-compute.git'
cookbook 'network',  git: 'https://github.com/mevansam/chef-cookbook-network.git'
cookbook 'storage',  git: 'https://github.com/mevansam/chef-cookbook-storage.git'
