## All services monkey patched to use upstart provider

default["upstart"]["services"] = [
    "keystone",
    "glance-registry",
    "glance-api",
    "cinder-volume",
    "cinder-scheduler",
    "cinder-group-active",
    "cinder-api",
    "ceilometer-agent-central",
    "ceilometer-api",
    "ceilometer-collector",
    "nova-api",
    "nova-api-ec2",
    "nova-api-os-compute",
    "nova-cert",
    "nova-scheduler",
    "nova-conductor",
    "nova-novncproxy",
    "nova-consoleauth",
    "nova-api-metadata",
    "nova-compute",
    "nova-network",
    "neutron-server",
    "neutron-lb-agent",
    "neutron-plugin-linuxbridge-agent",
    "neutron-plugin-openvswitch-agent",
    "neutron-openvswitch-switch",
    "openvswitch-switch",
    "iscsitarget"
]
